### ISSUE TITLE
Ratio of likes? 

### ISSUE THREAD

**Issue by quintendewilde** [ayushxx7/Facebook-Auto-Liker#1]
Hi love the simple script! 

Is there a way to give a ratio to like, so it doesn't like all pictures but some. Ex. like every 4-6 photo's? 

I'm not that code savvy to add this on my own though... :)

But this would be awesome!

**Comment by ayushxx7** [comment]
It would be easy to implement, I could do it, however, could you be more specific with the example (as in what exactly are you expecting when you say ratio) 
If you mean every 4th image should be liked that should be easy to implement. 
But do you mean, every 4th image irrespective of whether it is liked or not, or every 4th unliked image?

**Comment by ayushxx7** [comment]
```

pyautogui.hotkey('alt', 'tab') #switch to image
for z in range(0,100): #specify number of images (change 100) 
    time.sleep(0.2) #set processing time according to your pc & internet speed. 
    if z % 4 == 0 || z % 6 == 0: # change 4 or 6 to have likes at different points [add this for ratio of likes]
	    if (pyautogui.locateOnScreen('likeButtonOnFB.png')) != None: #check image is liked or not
	        pyautogui.press('l') #if image is opened pressing 'L' likes it. Thanks FB :) 
	    pyautogui.press('right') #move to next image
    time.sleep(0.2) #set processing time according to your pc & internet speed.

```
